version: "3.8"

services:
  myaiassistant-db:
    image: postgres:14
    container_name: myaiassistant-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 5

  myaiassistant-bot:
    build:
      context: .
    container_name: myaiassistant-bot
    depends_on:
      myaiassistant-db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "6789:6789"
    restart: always
    volumes:
      - ./src:/app/src
